CREATE TABLE "USysPg1" (
  "ProjectID" TEXT,
  "PlotNumber" TEXT,
  "FieldNumber" TEXT,
  "SiteSurveyor" TEXT,
  "Location" TEXT,
  "Zone" TEXT,
  "SubstrateDecWood" TEXT,
  "SubstrateBedRock" TEXT,
  "Longitude" TEXT,
  "FSRegionDistrict" TEXT,
  "NtsMapSheet" TEXT,
  "UTMZone" TEXT,
  "Date" TIMESTAMP,
  "Ecosection" TEXT,
  "Latitude" TEXT,
  "UTMNorthing" TEXT,
  "LocationAccuracy" TEXT,
  "YCoord" TEXT,
  "XCoord" TEXT,
  "AirPhotoNum" TEXT,
  "SiteSeries" TEXT,
  "RealmClass" TEXT,
  "TransDistrib" TEXT,
  "MapUnit" TEXT,
  "SubZone" TEXT,
  "MoistureRegime" TEXT,
  "NutrientRegime" TEXT,
  "SuccessionalStatus" TEXT,
  "StructuralStage" TEXT,
  "Submit_by_Email" TEXT,
  "StandAge" TEXT,
  "PlotRepresenting" TEXT,
  "Pic1" TEXT,
  "SiteDisturbance1" TEXT,
  "SiteDisturbance3" TEXT,
  "SiteDisturbance2" TEXT,
  "Exposure1" TEXT,
  "Exposure2" TEXT,
  "SiteNotes" TEXT,
  "SubstrateOrganicMatter" TEXT,
  "SubstrateWater" TEXT,
  "SubstrateMineralSoil" TEXT,
  "SubstrateRocks" TEXT,
  "Elevation" TEXT,
  "SlopeGradient" TEXT,
  "Aspect" TEXT,
  "MesoSlopePosition" TEXT,
  "SurfaceShape" TEXT,
  "Photo" TEXT,
  "UTMEasting" TEXT,
  "SurfaceTopographySize" TEXT,
  "SurfaceTopographyType" TEXT,
  "PDFversion" TEXT
);

CREATE INDEX "idx_USysPg1_AirPhotoNum" ON "USysPg1" ("AirPhotoNum");
CREATE INDEX "idx_USysPg1_ProjectID" ON "USysPg1" ("ProjectID");
