test_that("session logging closes only its precise concurrent login row", {
  con_check <- tryCatch(vpro_db_connect(install_extensions = FALSE), error = identity)
  if (inherits(con_check, "error")) skip(conditionMessage(con_check))
  vpro_db_disconnect(con_check)
  root <- withr::local_tempdir()
  withr::local_options(
    vpro.data_dir = file.path(root, "data"),
    vpro.config_dir = file.path(root, "config")
  )
  vpro_install()
  con <- vpro_db_connect()
  withr::defer(vpro_db_disconnect(con))
  context <- vpro_project_context(con = con)
  vpro_db_attach(con, vpro_db_path(c("VPro64", "VLists", "VUser", "VMetaData", "VMessageBoard")))
  vpro:::vpro_startup_reference_views(context)

  first <- vpro:::vpro_session_login(context, "tester", "host", as.POSIXct("2026-01-01 10:00:00", tz = "UTC"))
  second <- vpro:::vpro_session_login(context, "tester", "host", as.POSIXct("2026-01-01 10:01:00", tz = "UTC"))
  expect_false(identical(first$rowid, second$rowid))
  expect_identical(vpro:::vpro_session_open(context)$rowid, c(first$rowid, second$rowid))
  expect_true(vpro:::vpro_session_logout(context, first, as.POSIXct("2026-01-01 11:00:00", tz = "UTC")))
  expect_identical(vpro:::vpro_session_open(context)$rowid, second$rowid)
  expect_false(vpro:::vpro_session_logout(context, first))
})

test_that("project lifecycle logging uses explicit context user and reference descriptions atomically", {
  con_check <- tryCatch(vpro_db_connect(install_extensions = FALSE), error = identity)
  if (inherits(con_check, "error")) skip(conditionMessage(con_check))
  vpro_db_disconnect(con_check)
  root <- withr::local_tempdir()
  project_path <- file.path(root, "AuditProject.db")
  lists_path <- file.path(root, "VLists.db")
  file.copy(system.file("extdata", "projects", "Sample.db", package = "vpro"), project_path)
  file.copy(system.file("extdata", "VLists.db", package = "vpro"), lists_path)
  sqlite <- DBI::dbConnect(RSQLite::SQLite(), project_path)
  DBI::dbExecute(sqlite, 'DELETE FROM "Sample_Audit"')
  DBI::dbDisconnect(sqlite)
  con <- vpro_db_connect()
  withr::defer(vpro_db_disconnect(con))
  context <- vpro_project_context(con = con)
  vpro_db_attach(con, lists_path)
  vpro_project_attach(context, project_path, "Sample")
  vpro_project_activate(context, "Sample")

  changed <- vpro:::vpro_project_log_lifecycle(context, "explicit-user", "Open", as.POSIXct("2026-01-01", tz = "UTC"))
  expect_identical(changed$Table, c("USysAllSpecs", "USysTableOfLists"))
  vpro:::vpro_project_log_lifecycle(context, "explicit-user", "On", as.POSIXct("2026-01-02", tz = "UTC"))
  vpro:::vpro_project_log_lifecycle(context, "explicit-user", "Off", as.POSIXct("2026-01-03", tz = "UTC"))
  vpro:::vpro_project_log_lifecycle(context, "explicit-user", "Close", as.POSIXct("2026-01-04", tz = "UTC"))
  sqlite <- DBI::dbConnect(RSQLite::SQLite(), project_path)
  withr::defer(DBI::dbDisconnect(sqlite))
  rows <- DBI::dbGetQuery(sqlite, 'SELECT "User", "Table", "BeforeEdit", "AfterEdit" FROM "Sample_Audit" ORDER BY rowid')
  expect_identical(rows$User, rep("explicit-user", 6L))
  expect_identical(rows$Table, c("Open", "USysAllSpecs", "USysTableOfLists", "On", "Off", "Close"))
  expect_identical(rows$BeforeEdit[2:3], c("Unknown", "Unknown"))

  DBI::dbExecute(
    sqlite,
    paste('CREATE TRIGGER abort_reference BEFORE INSERT ON "Sample_Audit"', 'WHEN NEW."Table" = \'USysTableOfLists\' BEGIN SELECT RAISE(ABORT, \'blocked\'); END')
  )
  DBI::dbExecute(sqlite, 'DELETE FROM "Sample_Audit"')
  expect_error(vpro:::vpro_project_log_lifecycle(context, "explicit-user", "Open"), "blocked")
  expect_identical(DBI::dbGetQuery(sqlite, 'SELECT COUNT(*) AS n FROM "Sample_Audit"')$n, 0L)
})
