short_layers_fixture <- function() {
  project <- tempfile(fileext = ".db")
  su <- tempfile(fileext = ".db")
  ref <- tempfile(fileext = ".db")
  withr::defer(unlink(c(project, su, ref)), envir = parent.frame())
  con <- DBI::dbConnect(RSQLite::SQLite(), project)
  DBI::dbExecute(con, 'CREATE TABLE "Alpha_Env" ("PlotNumber" TEXT)')
  DBI::dbExecute(con, 'CREATE TABLE "Alpha_Admin" ("Plot" TEXT, "SitePlotQuality" TEXT, "VegPlotQuality" TEXT, "SoilPlotQuality" TEXT, "BEC_Use" TEXT)')
  DBI::dbExecute(con, 'CREATE TABLE "Alpha_Audit" ("EditWhen" TEXT)')
  for (suffix in c("Humus", "Metadata", "Mineral", "Other")) {
    DBI::dbExecute(con, paste0('CREATE TABLE "Alpha_', suffix, '" ("PlotNumber" TEXT)'))
  }
  fields <- paste0('"Cover', c(1:5, "5a", "5b", "5c", 6:7), '" REAL', collapse = ", ")
  DBI::dbExecute(con, paste0('CREATE TABLE "Alpha_Veg" ("ID" INTEGER, "PlotNumber" TEXT, "Species" TEXT, ', fields, ', "TotalA" REAL, "HeightA" REAL, "TotalB" REAL, "HeightB" TEXT, "Height6" REAL, "Cover8" REAL, "Cover9" REAL, "Collected" TEXT)'))
  DBI::dbExecute(con, 'CREATE TABLE "_table_metadata" ("table_name" TEXT, "description" TEXT)')
  DBI::dbExecute(con, "INSERT INTO _table_metadata VALUES ('Alpha_Env', 'VP08')")
  for (plot in c("P1", "P2", "P3")) {
    DBI::dbExecute(con, 'INSERT INTO "Alpha_Env" VALUES (?)', params = list(plot))
    DBI::dbExecute(con, 'INSERT INTO "Alpha_Admin" VALUES (?, ?, ?, ?, ?)',
                   params = list(plot, if (plot == "P2") "Poor" else "Good", "Good", "Good", "2"))
  }
  DBI::dbExecute(con, 'INSERT INTO "Alpha_Veg" ("PlotNumber", "Species", "Cover1", "Cover5a", "Cover7") VALUES (\'P1\', \'sp\', 1, 0, NULL)')
  DBI::dbExecute(con, 'INSERT INTO "Alpha_Veg" ("PlotNumber", "Species", "Cover1", "Cover5a", "Cover7") VALUES (\'P1\', \'sp\', 3, NULL, 4)')
  DBI::dbExecute(con, 'INSERT INTO "Alpha_Veg" ("PlotNumber", "Species", "Cover1") VALUES (\'P2\', \'sp\', 2)')
  DBI::dbExecute(con, 'INSERT INTO "Alpha_Veg" ("PlotNumber", "Species", "Cover1") VALUES (\'P3\', \'sp\', 9)')
  DBI::dbDisconnect(con)
  con <- DBI::dbConnect(RSQLite::SQLite(), su)
  DBI::dbExecute(con, 'CREATE TABLE "Subset_SU" ("PlotNumber" TEXT, "SiteUnit" TEXT)')
  for (row in list(c("P1", "U"), c("P1", "U"), c("P2", "U"), c("ORPHAN", "U"),
                   c("P1", "V"), c(NA, "U"), c("", "U"), c("  ", "U"),
                   c("P3", ""), c("P3", NA))) {
    DBI::dbExecute(con, 'INSERT INTO "Subset_SU" VALUES (?, ?)', params = as.list(row))
  }
  DBI::dbDisconnect(con)
  con <- DBI::dbConnect(RSQLite::SQLite(), ref)
  DBI::dbExecute(con, 'CREATE TABLE "USysTableOfLists" ("ListName" TEXT, "Item" TEXT, "ItemOrder" REAL)')
  for (i in seq_along(c("Poor", "Good"))) {
    DBI::dbExecute(con, 'INSERT INTO "USysTableOfLists" VALUES (\'DataQuality\', ?, ?)',
                   params = list(c("Poor", "Good")[[i]], i))
  }
  DBI::dbDisconnect(con)
  coordinator <- tryCatch(vpro_db_connect(), error = identity)
  if (inherits(coordinator, "error")) testthat::skip(conditionMessage(coordinator))
  withr::defer(vpro_db_disconnect(coordinator), envir = parent.frame())
  context <- vpro_project_context(con = coordinator)
  vpro_project_attach(context, project, "Alpha")
  vpro_project_activate(context, "Alpha")
  vpro_su_attach(context, su, "Subset")
  vpro_su_activate(context, "Subset")
  list(context = context, project = project, su = su, ref = ref)
}

test_that("short layers preserve max, non-null zero, cross-unit membership and orphans", {
  fixture <- short_layers_fixture()
  mapping <- vpro:::vpro_bundled_file("extdata", "short-veg-layer-mapping-v1.sqlite")
  paths <- c(fixture$project, fixture$su, fixture$ref, mapping)
  hashes <- unname(tools::md5sum(paths))
  out <- vpro_report_short_veg_layers(fixture$context, reference_path = "absent.db")
  expect_identical(out$units, data.frame(SiteUnit = c("U", "V"), n_plots = c(3L, 1L)))
  expect_identical(out$rows$layer, c("1", "5a", "7", "1", "1", "5a", "7"))
  expect_identical(out$rows$cover, c(3, 0, 4, 2, 3, 0, 4))
  expect_identical(out$rows$layer_code[out$rows$layer == "5a"], c("05a", "05a"))
  expect_identical(out$rows$strata[out$rows$layer == "7"], c("D", "D"))
  expect_identical(out$diagnostics$duplicate_membership_rows, 1L)
  expect_identical(out$diagnostics$excluded_null_or_blank_plot_rows, 3L)
  expect_identical(out$diagnostics$excluded_null_or_blank_unit_rows, 2L)
  expect_false(out$diagnostics$quality_applied)
  expect_identical(out$diagnostics$mapping_version, "access-layercode-v1")
  expect_identical(unname(tools::md5sum(paths)), hashes)
})

test_that("nullable species are retained and deterministically sorted", {
  fixture <- short_layers_fixture()
  con <- DBI::dbConnect(RSQLite::SQLite(), fixture$project)
  DBI::dbExecute(con, 'INSERT INTO "Alpha_Veg" ("PlotNumber", "Species", "Cover1") VALUES (\'P1\', NULL, 5)')
  DBI::dbDisconnect(con)

  out <- vpro_report_short_veg_layers(fixture$context)
  null_species <- out$rows[out$rows$PlotNumber == "P1" & is.na(out$rows$Species), , drop = FALSE]
  expect_identical(null_species$SiteUnit, c("U", "V"))
  expect_identical(null_species$layer, c("1", "1"))
  expect_identical(null_species$cover, c(5, 5))
})

test_that("quality is opt-in, removes failed and orphan membership with diagnostics", {
  fixture <- short_layers_fixture()
  paths <- c(fixture$project, fixture$su, fixture$ref)
  hashes <- unname(tools::md5sum(paths))
  out <- vpro_report_short_veg_layers(fixture$context, enforce_quality = TRUE,
                                      reference_path = fixture$ref, site_min = "Good")
  expect_identical(out$units, data.frame(SiteUnit = c("U", "V"), n_plots = c(1L, 1L)))
  expect_identical(unique(out$rows$PlotNumber), "P1")
  expect_true(all(c("ORPHAN", "P2") %in% out$diagnostics$quality_removed$PlotNumber))
  expect_true(out$diagnostics$quality_applied)
  expect_identical(out$diagnostics$duplicate_membership_rows, 1L)
  expect_identical(unname(tools::md5sum(paths)), hashes)
})

test_that("empty eligible membership retains typed outputs and needs an active SU", {
  fixture <- short_layers_fixture()
  con <- DBI::dbConnect(RSQLite::SQLite(), fixture$su)
  DBI::dbExecute(con, 'DELETE FROM "Subset_SU"')
  DBI::dbDisconnect(con)
  out <- vpro_report_short_veg_layers(fixture$context)
  expect_identical(out$rows, vpro:::vpro_short_veg_empty_rows())
  expect_identical(out$units, data.frame(SiteUnit = character(), n_plots = integer()))
  expect_identical(out$diagnostics$eligible_memberships, 0L)
  vpro_su_deactivate(fixture$context)
  expect_error(vpro_report_short_veg_layers(fixture$context), "active VPRO SU")
})

test_that("mapping and Veg schema failures are explicit and never mutate sources", {
  fixture <- short_layers_fixture()
  mapping <- tempfile(fileext = ".sqlite")
  withr::defer(unlink(mapping), envir = parent.frame())
  file.copy(vpro:::vpro_bundled_file("extdata", "short-veg-layer-mapping-v1.sqlite"), mapping)
  before <- unname(tools::md5sum(c(fixture$project, fixture$su, mapping)))
  expect_error(vpro_report_short_veg_layers(fixture$context, mapping_path = "missing.db"), "does not exist")
  con <- DBI::dbConnect(RSQLite::SQLite(), mapping)
  DBI::dbExecute(con, "UPDATE mapping_set SET version = 'other'")
  DBI::dbDisconnect(con)
  expect_error(vpro_report_short_veg_layers(fixture$context, mapping_path = mapping), "version")
  con <- DBI::dbConnect(RSQLite::SQLite(), mapping)
  DBI::dbExecute(con, "UPDATE mapping_set SET version = 'access-layercode-v1', source_sha256 = 'bad'")
  DBI::dbDisconnect(con)
  expect_error(vpro_report_short_veg_layers(fixture$context, mapping_path = mapping), "SHA256")
  con <- DBI::dbConnect(RSQLite::SQLite(), mapping)
  DBI::dbExecute(con, "UPDATE mapping_set SET source_sha256 = '8a03d48c3a7f0e0a2e0868569969ad91603b124ce38febb38b5a3b284e99d510'")
  DBI::dbExecute(con, "UPDATE layer_mapping SET Layer1234567 = NULL WHERE Layer1234567 = '1'")
  DBI::dbDisconnect(con)
  expect_error(vpro_report_short_veg_layers(fixture$context, mapping_path = mapping), "mapping")
  con <- DBI::dbConnect(RSQLite::SQLite(), mapping)
  DBI::dbExecute(con, "UPDATE layer_mapping SET Layer1234567 = '1' WHERE LayerCode = '02'")
  DBI::dbDisconnect(con)
  expect_error(vpro_report_short_veg_layers(fixture$context, mapping_path = mapping), "mapping")
  con <- DBI::dbConnect(RSQLite::SQLite(), mapping)
  DBI::dbExecute(con, "UPDATE layer_mapping SET Layer1234567 = '2' WHERE LayerCode = '02'")
  DBI::dbExecute(con, "UPDATE layer_mapping SET Layer1234567 = '1', LayerCode = '99' WHERE LayerCode = '01'")
  DBI::dbDisconnect(con)
  expect_error(vpro_report_short_veg_layers(fixture$context, mapping_path = mapping), "mapping")
  expect_identical(unname(tools::md5sum(c(fixture$project, fixture$su))), before[1:2])
  con <- DBI::dbConnect(RSQLite::SQLite(), fixture$project)
  DBI::dbExecute(con, 'ALTER TABLE "Alpha_Veg" RENAME COLUMN "Cover7" TO "Other"')
  DBI::dbDisconnect(con)
  expect_error(vpro_report_short_veg_layers(fixture$context), "Cover7")
})
