# Plot vegetation records ---------------------------------------------------

vpro_plot_vegetation_validate_create <- function(values) {
  species <- values$Species
  if (
    is.null(species) ||
      length(species) != 1L ||
      is.na(species) ||
      !is.character(species) ||
      !nzchar(trimws(species)) ||
      nchar(species) > 8L
  ) {
    stop("`values$Species` must be one nonblank character value of at most 8 characters.", call. = FALSE)
  }
  invisible(TRUE)
}

#' List vegetation records for one plot in the active VPRO project
#'
#' Reads canonical `_Veg` rows corresponding to Access's `USysVeg` record
#' source. Rows are ordered by species and then ID. Active site-unit filtering
#' does not hide base-project rows.
#'
#' @param context A VPRO project context with an active project.
#' @param plot_number Plot identifier.
#'
#' @return A data frame containing the plot's vegetation rows.
#' @export
vpro_plot_vegetation_list <- function(context, plot_number) {
  record <- vpro_plot_active(context)
  plot_number <- vpro_plot_number(plot_number)
  vpro_plot_get(context, plot_number)

  con <- DBI::dbConnect(RSQLite::SQLite(), record$path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)
  table <- vpro_project_table(record$project, "Veg")
  sql <- paste(
    "SELECT * FROM",
    DBI::dbQuoteIdentifier(con, table),
    "WHERE",
    DBI::dbQuoteIdentifier(con, "PlotNumber"),
    "= ? ORDER BY",
    DBI::dbQuoteIdentifier(con, "Species"),
    ",",
    DBI::dbQuoteIdentifier(con, "ID")
  )
  DBI::dbGetQuery(con, sql, params = list(plot_number))
}

#' Read one vegetation record from the active VPRO project
#'
#' Reads one `_Veg` row by plot and signed 32-bit ID. Access permits duplicate
#' vegetation IDs, including within one plot, so the operation requires exactly
#' one matching row and fails safely when the identity is ambiguous.
#'
#' @inheritParams vpro_plot_vegetation_list
#' @param id Existing `_Veg` child-row ID.
#'
#' @return A one-row data frame.
#' @export
vpro_plot_vegetation_get <- function(context, plot_number, id) {
  record <- vpro_plot_active(context)
  plot_number <- vpro_plot_number(plot_number)
  id <- vpro_plot_child_id(id)
  vpro_plot_get(context, plot_number)

  con <- DBI::dbConnect(RSQLite::SQLite(), record$path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)
  row <- vpro_plot_child_row(
    con,
    vpro_project_table(record$project, "Veg"),
    plot_number,
    id
  )
  vpro_plot_child_assert_row(row, "vegetation", plot_number, id)
  row
}

#' Create one vegetation record in the active VPRO project
#'
#' Creates a canonical `_Veg` row with a collision-checked signed 32-bit ID.
#' A nonblank species code of at most eight characters is required. At audit
#' strength 2 or 3, populated fields are audited with the generated child ID in
#' the same transaction.
#'
#' @inheritParams vpro_plot_vegetation_list
#' @param values Named list of field values for the new row. `Species` is
#'   required; `PlotNumber` and `ID` are generated by the operation.
#' @param user Stable user identity for audit rows. Defaults to `Current.User`
#'   from the context configuration when available.
#' @param audit_strength Integer from 0 through 3. Defaults to
#'   `Audit.AuditStrength` from configuration, then 1 when unavailable.
#'
#' @return A list containing the created vegetation row and audit rows written,
#'   invisibly.
#' @export
vpro_plot_vegetation_create <- function(
  context,
  plot_number,
  values,
  user = NULL,
  audit_strength = NULL
) {
  result <- vpro_plot_child_create(
    context,
    plot_number,
    values,
    "Veg",
    "_Veg",
    "vpro_plot_vegetation_create",
    user,
    audit_strength,
    vpro_plot_vegetation_validate_create
  )
  names(result)[[1L]] <- "vegetation"
  invisible(result)
}

#' Update one vegetation record in the active VPRO project
#'
#' Updates exactly one existing `_Veg` row identified by plot and ID and writes
#' qualifying field-level audit rows in the same SQLite transaction. Species
#' may change while the generated ID remains stable. Because legacy Access
#' permits duplicate IDs, ambiguous identities are rejected without mutation.
#'
#' @inheritParams vpro_plot_vegetation_create
#' @param id Existing `_Veg` child-row ID.
#' @param changes Named list of field values to update.
#'
#' @return A list containing the updated vegetation row and audit rows written,
#'   invisibly.
#' @export
vpro_plot_vegetation_update <- function(
  context,
  plot_number,
  id,
  changes,
  user = NULL,
  audit_strength = NULL
) {
  record <- vpro_plot_active(context)
  plot_number <- vpro_plot_number(plot_number)
  id <- vpro_plot_child_id(id)
  changes <- vpro_plot_changes(changes, "changes")
  if (length(changes) == 0L) {
    stop("At least one vegetation field update is required.", call. = FALSE)
  }
  if (any(c("PlotNumber", "ID") %in% names(changes))) {
    stop("Vegetation record keys are immutable in `vpro_plot_vegetation_update()`.", call. = FALSE)
  }
  if ("Species" %in% names(changes)) {
    vpro_plot_vegetation_validate_create(list(Species = changes$Species))
  }
  user <- vpro_plot_user(context, user)
  audit_strength <- vpro_plot_audit_strength(context, audit_strength)
  vpro_plot_get(context, plot_number)

  con <- DBI::dbConnect(RSQLite::SQLite(), record$path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)
  DBI::dbExecute(con, "PRAGMA foreign_keys = ON")
  tables <- list(
    vegetation = vpro_project_table(record$project, "Veg"),
    audit = vpro_project_table(record$project, "Audit")
  )
  changes <- vpro_plot_child_validate_changes(
    con,
    tables$vegetation,
    changes,
    "vegetation",
    "vpro_plot_vegetation_update"
  )

  result <- DBI::dbWithTransaction(con, {
    before_row <- vpro_plot_child_row(
      con,
      tables$vegetation,
      plot_number,
      id
    )
    vpro_plot_child_assert_row(before_row, "vegetation", plot_number, id)
    before <- unname(as.list(before_row[1, names(changes), drop = FALSE]))
    assignments <- paste(
      DBI::dbQuoteIdentifier(con, names(changes)),
      "= ?",
      collapse = ", "
    )
    sql <- paste(
      "UPDATE",
      DBI::dbQuoteIdentifier(con, tables$vegetation),
      "SET",
      assignments,
      "WHERE",
      DBI::dbQuoteIdentifier(con, "PlotNumber"),
      "= ? AND",
      DBI::dbQuoteIdentifier(con, "ID"),
      "= ?"
    )
    updated <- DBI::dbExecute(
      con,
      sql,
      params = c(unname(changes), list(plot_number, id))
    )
    if (updated != 1L) {
      stop("VPRO vegetation update did not affect exactly one row.", call. = FALSE)
    }
    after_row <- vpro_plot_child_row(
      con,
      tables$vegetation,
      plot_number,
      id
    )
    after <- unname(as.list(after_row[1, names(changes), drop = FALSE]))
    audit <- vpro_plot_child_audit_rows(
      record$project,
      user,
      plot_number,
      "_Veg",
      names(changes),
      before,
      after,
      id,
      audit_strength
    )
    if (nrow(audit) > 0L) {
      DBI::dbAppendTable(con, tables$audit, audit)
    }
    changed <- !vapply(
      seq_along(after),
      function(i) vpro_plot_equal(before[[i]], after[[i]]),
      logical(1)
    )
    attr(audit, "changed_fields") <- names(changes)[changed]
    list(vegetation = after_row, audit = audit)
  })
  attr(result, "changed_fields") <- attr(result$audit, "changed_fields")
  invisible(result)
}

#' Delete one vegetation record from the active VPRO project
#'
#' Deletes exactly one existing `_Veg` row identified by plot and ID. Access
#' permits duplicate vegetation IDs, so ambiguous identities are rejected. The
#' observed bound-form workflow does not add audit rows for row deletion.
#'
#' @inheritParams vpro_plot_vegetation_get
#'
#' @return The deleted row, invisibly.
#' @export
vpro_plot_vegetation_delete <- function(context, plot_number, id) {
  vpro_plot_child_delete(context, plot_number, id, "Veg", "vegetation")
}
